### ISSUE TITLE
Error in azure.LogAnalyticsAppender

### ISSUE THREAD

**Issue by ddeuchert** [FollettSchoolSolutions/perfmon4j#30]
Getting this exception in in 1.6.0-SNAPSHOT

23:42:00,002 ERROR [org.perfmon4j.SnapShotMonitor] (PerfMon.utilityTimer) Error appending snapshot data for monitor: Composite Memory Pool: java.lang.IllegalStateException: Timer already cancelled.
	at java.base/java.util.Timer.sched(Timer.java:398)
	at java.base/java.util.Timer.schedule(Timer.java:194)
	at org.perfmon4j.azure.LogAnalyticsAppender.appendDataLine(LogAnalyticsAppender.java:210)
	at org.perfmon4j.azure.LogAnalyticsAppender.outputData(LogAnalyticsAppender.java:231)
	at org.perfmon4j.Appender.appendData(Appender.java:194)
	at org.perfmon4j.SnapShotMonitor$MonitorTimerTask.failSafeRun(SnapShotMonitor.java:151)
	at org.perfmon4j.util.FailSafeTimerTask.run(FailSafeTimerTask.java:31)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by ddeuchert** [comment]
Could not reproduce issue.  Still replaced usage of the Timer class with a ScheduledExecutorService.
