### ISSUE TITLE
POJOSnapShotMonitor should not throw exception on failure to instrument method

### ISSUE THREAD

**Issue by ddeuchert** [FollettSchoolSolutions/perfmon4j#45]
Currently any @SnapShotGauge, @SnapShotCounter, or @SnapShotString annotations are expected to be put on a method starting with "get"

We should:

1. Support "is" methods for boolean gauges.
2. More importantly only WARN on not being able to instrument the method.  Never throw an exception, simply ignore the method if all else fails.

Example of an exception:
Caused by: java.lang.RuntimeException: org.perfmon4j.instrument.snapshot.GenerateSnapShotException: Error generating SnapShotDataImpl
	at api.org.perfmon4j.agent.POJOSnapShotRegistry.register(POJOSnapShotRegistry.java)
	at api.org.perfmon4j.agent.POJOSnapShotRegistry.register(POJOSnapShotRegistry.java:20)
	at com.follettsoftware.async.emailer.impl.EmailerSingletonImpl.<init>(EmailerSingletonImpl.java:46)
	... 31 more
Caused by: org.perfmon4j.instrument.snapshot.GenerateSnapShotException: Error generating SnapShotDataImpl
	at org.perfmon4j.instrument.snapshot.JavassistSnapShotGenerator.generateSnapShotDataImpl(JavassistSnapShotGenerator.java:562)
	at org.perfmon4j.instrument.snapshot.JavassistSnapShotGenerator.generateBundleForPOJO(JavassistSnapShotGenerator.java:581)
	at org.perfmon4j.POJOSnapShotRegistry.buildRegistryEntry(POJOSnapShotRegistry.java:21)
	at org.perfmon4j.GenericItemRegistry.register(GenericItemRegistry.java:33)
	... 34 more
Caused by: java.lang.IllegalArgumentException: Invalid method expected expected to start with get
	at org.perfmon4j.instrument.snapshot.JavassistSnapShotGenerator.generateFieldName(JavassistSnapShotGenerator.java:71)
	at org.perfmon4j.instrument.snapshot.JavassistSnapShotGenerator.generateGauge(JavassistSnapShotGenerator.java:178)
	at org.perfmon4j.instrument.snapshot.JavassistSnapShotGenerator.generateSnapShotDataImpl(JavassistSnapShotGenerator.java:494)
	... 37 more

**Comment by ddeuchert** [comment]
To take this to the next level, there should NEVER be any exceptions thrown out of POJOSnapShotRegistry.register() or POJOSnapShotRegistry.deRegister().
If for any reason a SnapShotRegistration fails it should quietly WARN and eat the exception.

**Comment by ddeuchert** [comment]
Added support for "issers"  Commit id: 1dfc5c8d98cf49aed01df3c586c9c71e42c82e24

**Comment by ddeuchert** [comment]
Fixed will be included in release 2.0.2.

Addressed this issue when using "api.org.perfmon4j.agent.POJOSnapShotRegistry.register(pojo)". Now if you register a POJO that fails to generate a SnapShotMonitor (typically due to an error with a property annotation) 

Important: An exception will still be thrown if you are not going through the Agent and register directly with the implementation using:  org.perfmon4j.POJOSnapShotRegistry.register(pojo)
